#!/usr/bin/env bash
# Install the standalone theme engine. Software/package installation belongs to
# linux-setup (or the user's distro); this script only installs theme assets and
# chooses generators that are usable on the current machine.
set -euo pipefail

_src="${BASH_SOURCE[0]-}"
if [ -z "$_src" ] || [ ! -f "$_src" ]; then
    printf 'Downloading themes...\n'
    _tmpdir="$(mktemp -d)"
    trap 'rm -rf "$_tmpdir"' EXIT
    git clone --depth 1 https://github.com/grapes7000/themes.git "$_tmpdir/themes"
    bash "$_tmpdir/themes/install.sh" "$@"
    exit $?
fi

REPO="$(cd "$(dirname "$_src")" && pwd)"
CFG="${XDG_CONFIG_HOME:-$HOME/.config}"
BUILD_APPIMAGE=0
TARGET_MODE=auto

while [ "$#" -gt 0 ]; do
    case "$1" in
        --build-appimage) BUILD_APPIMAGE=1 ;;
        --targets)
            shift
            TARGET_MODE="${1:-}"
            case "$TARGET_MODE" in auto|terminal|full) ;; *) echo "--targets must be auto, terminal, or full" >&2; exit 2 ;; esac
            ;;
        --targets=*)
            TARGET_MODE="${1#*=}"
            case "$TARGET_MODE" in auto|terminal|full) ;; *) echo "--targets must be auto, terminal, or full" >&2; exit 2 ;; esac
            ;;
        -h|--help)
            cat <<'EOF'
Usage: ./install.sh [--targets auto|terminal|full] [--build-appimage]

  auto      detect the desktop and enable only usable generators (default)
  terminal  enable only portable terminal/editor generators that are installed
  full      enable the full Hyprland-oriented target set

This installer does not install distro packages or shell frameworks.
EOF
            exit 0
            ;;
        *) echo "Unknown option: $1" >&2; exit 2 ;;
    esac
    shift
done

mkdir -p "$CFG/hypr/themes" "$CFG/hypr/wallpapers" "$CFG/hypr/generated" "$HOME/.local/bin"
cp "$REPO"/themes/*.json "$CFG/hypr/themes/"
cp "$REPO"/wallpapers/*.png "$CFG/hypr/wallpapers/" 2>/dev/null || true

STUDIO_TMP="$(mktemp -d)"
trap 'rm -rf "$STUDIO_TMP"' EXIT
bash "$REPO/tools/unpack-theme-studio.sh" "$STUDIO_TMP" >/dev/null

install -m755 "$REPO/bin/theme" "$HOME/.local/bin/theme-legacy"
install -m755 "$REPO/bin/theme-studio" "$HOME/.local/bin/theme"
for t in theme-new theme-menu theme-uninstall wallgen starship-config theme-pywalfox theme-stylus theme-from-image; do
    install -m755 "$REPO/bin/$t" "$HOME/.local/bin/$t"
done
for module in theme_starship.py theme_effects.py theme_homepage.py theme_editor.py theme_runtime.py theme_ui.py; do
    install -m644 "$REPO/bin/$module" "$HOME/.local/bin/$module"
done
mkdir -p "$CFG/theme-engine/ui-styles"
install -m644 "$REPO"/ui-styles/*.json "$CFG/theme-engine/ui-styles/"
for module in theme_schema.py theme_preview.py theme_waybar.py theme_components.py theme_tui_widgets.py theme_tui.py; do
    install -m644 "$STUDIO_TMP/$module" "$HOME/.local/bin/$module"
done
mkdir -p "$HOME/.local/share/doc/theme-studio"
install -m644 "$STUDIO_TMP/THEME-STUDIO.md" "$HOME/.local/share/doc/theme-studio/README.md"
install -m644 "$STUDIO_TMP/Theme-Studio-TUI-Design-Plan.md" "$HOME/.local/share/doc/theme-studio/Design-Plan.md"

has() { command -v "$1" >/dev/null 2>&1; }
opt() { has "$2" && echo "$1" || echo "# $1"; }

detect_de() {
    if [ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ] || has hyprctl; then
        echo hyprland
    elif [ -n "${KDE_FULL_SESSION:-}" ] || [ "${XDG_CURRENT_DESKTOP:-}" = "KDE" ] || has plasmashell; then
        echo kde
    elif [ "${XDG_CURRENT_DESKTOP:-}" = "XFCE" ] || has xfce4-session; then
        echo xfce
    elif [ "${XDG_CURRENT_DESKTOP:-}" = "X-Cinnamon" ] || [ "${XDG_CURRENT_DESKTOP:-}" = "MATE" ] \
         || [ "${XDG_CURRENT_DESKTOP:-}" = "GNOME" ] || has cinnamon-session || has mate-session || has gnome-shell; then
        echo gtk-de
    else
        echo unknown
    fi
}

emit_terminal_targets() {
    opt kitty kitty
    opt starship starship
    opt nvim nvim
    opt zsh zsh
}

write_targets_conf() {
    local mode="$1" de="$2" out="$CFG/theme-engine/targets.conf"
    {
        echo "# Enabled theme targets (one per line). Comment out to disable."
        echo "# Generated by themes/install.sh --targets $mode (detected desktop: $de)."
        echo "# Edit freely -- install.sh will not overwrite an existing file."
        echo "# Package/software ownership belongs to linux-setup or your distro."
        case "$mode" in
            terminal)
                emit_terminal_targets
                ;;
            full)
                echo hypr
                echo waybar
                emit_terminal_targets
                echo wallpaper
                echo wofi
                echo rofi
                echo dunst
                echo hyprlock
                opt homepage eww
                ;;
            auto)
                case "$de" in
                    hyprland)
                        echo hypr
                        opt waybar waybar
                        emit_terminal_targets
                        opt wallpaper hyprpaper
                        opt wofi wofi
                        has wofi || opt rofi rofi
                        opt dunst dunst
                        opt hyprlock hyprlock
                        opt homepage eww
                        echo "# kde"
                        echo "# oomox"
                        echo "# gtk"
                        echo "# xfce"
                        ;;
                    kde)
                        emit_terminal_targets
                        opt kde plasma-apply-colorscheme
                        ;;
                    xfce)
                        emit_terminal_targets
                        echo xfce
                        if has oomox-cli; then echo oomox; else echo "# oomox"; echo gtk; fi
                        ;;
                    gtk-de)
                        emit_terminal_targets
                        if has oomox-cli; then echo oomox; else echo "# oomox"; echo gtk; fi
                        ;;
                    *)
                        emit_terminal_targets
                        ;;
                esac
                ;;
        esac
        echo "# obsidian=~/Documents/Obsidian Vault"
        echo "# firefox"
    } > "$out"
}

mkdir -p "$CFG/theme-engine"
if [ ! -f "$CFG/theme-engine/targets.conf" ]; then
    de="$(detect_de)"
    write_targets_conf "$TARGET_MODE" "$de"
    echo "Wrote $CFG/theme-engine/targets.conf (mode: $TARGET_MODE, detected: $de)."
else
    echo "Keeping existing $CFG/theme-engine/targets.conf."
fi

echo "Installed $(ls "$REPO"/themes/*.json | wc -l) themes + Theme Studio + generators."
if [[ ":$PATH:" != *":$HOME/.local/bin:"* ]]; then
    echo "~/.local/bin is not currently on PATH; add it through your shell config/dotfiles."
fi
echo "This installer does not edit shell rc files and does not install packages or Oh My Zsh."
echo "Open Theme Studio: theme"
echo "Apply a theme:      theme <name>"
echo "Validate current:   theme validate"

if [ "$BUILD_APPIMAGE" -eq 1 ]; then
    "$REPO/packaging/build-appimage.sh"
else
    echo "Optional portable build: ./install.sh --build-appimage"
fi
